theme: jekyll-theme-minimal
title: Covidstat
description: Get all the news and statistics on the Coronavirus pandemic.
logo: https://raw.githubusercontent.com/ir2pid/CovidStatApp/master/app_icon.png
show_downloads: false
